name = "Undigits"
uuid = "f0c79fe5-1a7a-479e-acee-f2ba26419045"
authors = ["John Lapeyre"]
version = "1.0.0"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
